const fileTypeIconMappingDefinition = {
    'default'            : {'icon': 'fa fa-file-o l-ui-text'             },
    'loading'            : {'icon': 'fa fa-hourglass-half l-ui-text'     },
    'folder'             : {'icon': 'fa fa-folder l-ui-text'             },
    'folder-open'        : {'icon': 'fa fa-folder-open l-ui-text'        },
    
    'ipynb'              : {'icon': 'l-jupyter-icon'                     },
    'py'                 : {'icon': 'l-python-icon'                      },
    'pyc'                : {'icon': 'devicon-python-plain l-sandybrown'  },
    'pyd'                : {'icon': 'devicon-python-plain l-sandybrown'  },
    'pyo'                : {'icon': 'devicon-python-plain l-sandybrown'  },
    'pyw'                : {'icon': 'devicon-python-plain l-sandybrown'  },
    'pyx'                : {'icon': 'devicon-python-plain l-yellow'      },
    'pxd'                : {'icon': 'devicon-python-plain l-brown'       },
    
    'ai'                 : {'icon': 'devicon-illustrator-plain colored'  },
    'c'                  : {'icon': 'devicon-c-plain colored'            },
    'cc'                 : {'icon': 'devicon-c-plain l-green'            },
    'class'              : {'icon': 'devicon-java-plain l-green'         },
    'coffee'             : {'icon': 'devicon-coffeescript-plain l-blue'  },
    'cpp'                : {'icon': 'devicon-cplusplus-plain colored'    },
    'cs'                 : {'icon': 'devicon-csharp-plain colored'       },
    'css'                : {'icon': 'devicon-css3-plain colored'         },
    'dockerfile'         : {'icon': 'devicon-docker-plain colored'       },
    'go'                 : {'icon': 'devicon-go-plain colored'           },
    'htm'                : {'icon': 'devicon-html5-plain l-orange'       },
    'html'               : {'icon': 'devicon-html5-plain colored'        },
    'java'               : {'icon': 'devicon-java-plain colored'         },
    'js'                 : {'icon': 'devicon-javascript-plain colored'   },
    'less'               : {'icon': 'devicon-less-plain-wordmark colored'},
    'php'                : {'icon': 'devicon-php-plain colored'          },
    'php3'               : {'icon': 'devicon-php-plain colored'          },
    'php4'               : {'icon': 'devicon-php-plain colored'          },
    'psd'                : {'icon': 'devicon-photoshop-plain colored'    },
    'rb'                 : {'icon': 'devicon-ruby-plain colored'         },
    'swift'              : {'icon': 'devicon-swift-plain colored'        },
    'ts'                 : {'icon': 'devicon-typescript-plain colored'   },
    
    '7z'                : {'icon': 'fa fa-archive l-olive'               },
    'aac'               : {'icon': 'fa fa-music l-yellow'                },
    'bat'               : {'icon': 'fa fa-terminal l-red'                },
    'bin'               : {'icon': 'fa fa-file l-red'                    },
    'cmd'               : {'icon': 'fa fa-terminal l-green'              },
    'config'            : {'icon': 'fa fa-cog l-green'                   },
    'csv'               : {'icon': 'fa fa-table l-green'                 },
    'db'                : {'icon': 'fa fa-database l-blue'               },
    'db2'               : {'icon': 'fa fa-database l-red'                },
    'db3'               : {'icon': 'fa fa-database l-green'              },
    'doc'               : {'icon': 'fa fa-file-word-o l-blue'            },
    'docx'              : {'icon': 'fa fa-file-word-o l-blue'            },
    'exe'               : {'icon': 'fa fa-windows l-orange'              },
    'flac'              : {'icon': 'fa fa-music l-green'                 },
    'gif'               : {'icon': 'fa fa-file-image-o l-olive'          },
    'gz'                : {'icon': 'fa fa-file-archive-o l-olive'        },
    'ico'               : {'icon': 'fa fa-file-image-o l-white'          },
    'ini'               : {'icon': 'fa fa-cog l-white'                   },
    'jpg'               : {'icon': 'fa fa-camera l-slate'                },
    'jpeg'              : {'icon': 'fa fa-camera l-slate'                },
    'json'              : {'icon': 'fa fa-cog l-orange'                  },
    'log'               : {'icon': 'fa fa-file-text-o l-white'           },
    'md'                : {'icon': 'fa fa-arrow-down l-white'            },
    'mid'               : {'icon': 'fa fa-music l-blue'                  },
    'midi'              : {'icon': 'fa fa-music l-blue'                  },
    'mp3'               : {'icon': 'fa fa-music l-red'                   },
    'mp4'               : {'icon': 'fa fa-film l-red'                    },
    'o'                 : {'icon': 'fa fa-object-ungroup l-white'        },
    'ogg'               : {'icon': 'fa fa-file-audio-o l-white'          },
    'png'               : {'icon': 'fa fa-picture-o l-red'               },
    'pkg'               : {'icon': 'fa fa-cube l-purple'                 },
    'ppt'               : {'icon': 'fa fa-file-powerpoint-o l-red'       },
    'pptx'              : {'icon': 'fa fa-file-powerpoint-o l-red'       },
    'rar'               : {'icon': 'fa fa-archive l-purple'              },
    'rs'                : {'icon': 'fa fa-cog l-gray'                    },
    'rst'               : {'icon': 'fa fa-align-left l-gray'             },
    'svg'               : {'icon': 'fa fa-file-image-o l-green'          },
    'sh'                : {'icon': 'fa fa-terminal l-white'              },
    'so'                : {'icon': 'fa fa-share-square l-gray'           },
    'tar'               : {'icon': 'fa fa-file-archive-o l-gray'         },
    'ttf'               : {'icon': 'fa fa-font l-orange'                 },
    'txt'               : {'icon': 'fa fa-file-text l-gray'              },
    'wav'               : {'icon': 'fa fa-volume-up l-blue'              },
    'woff'              : {'icon': 'fa fa-font l-blue'                   },
    'woff2'             : {'icon': 'fa fa-font l-red'                    },
    'xls'               : {'icon': 'fa fa-file-excel-o l-green'          },
    'xlsx'              : {'icon': 'fa fa-file-excel-o l-green'          },
    'xml'               : {'icon': 'fa fa-code l-orange'                 },
    'xz'                : {'icon': 'fa fa-archive l-red'                 },
    'yaml'              : {'icon': 'fa fa-percent l-red'                 },
    'zip'               : {'icon': 'fa fa-archive l-orange'              },
    
}

const mapToFileType = fileName => {
    const dotPosition = fileName.lastIndexOf('.')
    const extension = fileName.substring(dotPosition + 1)
    if (fileTypeIconMappingDefinition[extension] == undefined) return 'default'
    return extension
}

export {
    fileTypeIconMappingDefinition, mapToFileType
}